$AndroidOwnerDR = @"

{
    "@odata.type":  "#microsoft.graph.androidDeviceOwnerGeneralDeviceConfiguration",
    "deviceManagementApplicabilityRuleOsEdition":  null,
    "deviceManagementApplicabilityRuleOsVersion":  null,
    "deviceManagementApplicabilityRuleDeviceMode":  null,
    "description":  "PIN and screen lock, threat scan on apps",
    "displayName":  "Portall - Android Enterprise Owner - Device restrictions",
    "accountsBlockModification":  null,
    "appsAllowInstallFromUnknownSources":  null,
    "appsAutoUpdatePolicy":  "notConfigured",
    "appsDefaultPermissionPolicy":  "prompt",
    "appsRecommendSkippingFirstUseHints":  null,
    "bluetoothBlockConfiguration":  null,
    "bluetoothBlockContactSharing":  null,
    "cameraBlocked":  null,
    "cellularBlockWiFiTethering":  null,
    "certificateCredentialConfigurationDisabled":  null,
    "dataRoamingBlocked":  null,
    "dateTimeConfigurationBlocked":  null,
    "factoryResetDeviceAdministratorEmails":  [

                                                ],
    "factoryResetBlocked":  null,
    "globalProxy":  null,
    "googleAccountsBlocked":  null,
    "kioskModeScreenSaverConfigurationEnabled":  null,
    "kioskModeScreenSaverImageUrl":  null,
    "kioskModeScreenSaverDisplayTimeInSeconds":  null,
    "kioskModeScreenSaverStartDelayInSeconds":  null,
    "kioskModeScreenSaverDetectMediaDisabled":  null,
    "kioskModeWallpaperUrl":  null,
    "kioskModeExitCode":  null,
    "kioskModeVirtualHomeButtonEnabled":  null,
    "kioskModeVirtualHomeButtonType":  null,
    "kioskModeBluetoothConfigurationEnabled":  null,
    "kioskModeWiFiConfigurationEnabled":  null,
    "kioskModeFlashlightConfigurationEnabled":  null,
    "kioskModeMediaVolumeConfigurationEnabled":  null,
    "microphoneForceMute":  null,
    "networkEscapeHatchAllowed":  null,
    "nfcBlockOutgoingBeam":  null,
    "passwordBlockKeyguard":  null,
    "passwordBlockKeyguardFeatures":  [

                                        ],
    "passwordExpirationDays":  null,
    "passwordMinimumLength":  4,
    "passwordMinimumLetterCharacters":  null,
    "passwordMinimumLowerCaseCharacters":  null,
    "passwordMinimumNonLetterCharacters":  null,
    "passwordMinimumNumericCharacters":  null,
    "passwordMinimumSymbolCharacters":  null,
    "passwordMinimumUpperCaseCharacters":  null,
    "passwordMinutesOfInactivityBeforeScreenTimeout":  5,
    "passwordPreviousPasswordCountToBlock":  null,
    "passwordRequiredType":  "numeric",
    "passwordSignInFailureCountBeforeFactoryReset":  10,
    "playStoreMode":  null,
    "safeBootBlocked":  null,
    "screenCaptureBlocked":  null,
    "securityAllowDebuggingFeatures":  null,
    "securityRequireVerifyApps":  true,
    "statusBarBlocked":  null,
    "stayOnModes":  [

                    ],
    "storageAllowUsb":  null,
    "storageBlockExternalMedia":  null,
    "storageBlockUsbFileTransfer":  null,
    "systemUpdateWindowStartMinutesAfterMidnight":  null,
    "systemUpdateWindowEndMinutesAfterMidnight":  null,
    "systemUpdateInstallType":  null,
    "systemWindowsBlocked":  null,
    "usersBlockAdd":  null,
    "usersBlockRemove":  null,
    "volumeBlockAdjustment":  null,
    "vpnAlwaysOnLockdownMode":  false,
    "vpnAlwaysOnPackageIdentifier":  "",
    "wifiBlockEditConfigurations":  null,
    "wifiBlockEditPolicyDefinedConfigurations":  null,
    "kioskModeApps":  [

                        ]
}
"@