$AndroidWorkDR = @"

{
    "@odata.type":  "#microsoft.graph.androidWorkProfileGeneralDeviceConfiguration",
    "deviceManagementApplicabilityRuleOsEdition":  null,
    "deviceManagementApplicabilityRuleOsVersion":  null,
    "deviceManagementApplicabilityRuleDeviceMode":  null,
    "description":  "Password on work profile, prevent unknown app sources",
    "displayName":  "Portall - Android Enterprise Work - Device restrictions",
    "passwordBlockFingerprintUnlock":  false,
    "passwordBlockTrustAgents":  false,
    "passwordExpirationDays":  null,
    "passwordMinimumLength":  null,
    "passwordMinutesOfInactivityBeforeScreenTimeout":  null,
    "passwordPreviousPasswordBlockCount":  null,
    "passwordSignInFailureCountBeforeFactoryReset":  null,
    "passwordRequiredType":  "deviceDefault",
    "workProfileDataSharingType":  "deviceDefault",
    "workProfileBlockNotificationsWhileDeviceLocked":  false,
    "workProfileBlockAddingAccounts":  false,
    "workProfileBluetoothEnableContactSharing":  false,
    "workProfileBlockScreenCapture":  false,
    "workProfileBlockCrossProfileCallerId":  false,
    "workProfileBlockCamera":  false,
    "workProfileBlockCrossProfileContactsSearch":  false,
    "workProfileBlockCrossProfileCopyPaste":  false,
    "workProfileDefaultAppPermissionPolicy":  "prompt",
    "workProfilePasswordBlockFingerprintUnlock":  false,
    "workProfilePasswordBlockTrustAgents":  false,
    "workProfilePasswordExpirationDays":  null,
    "workProfilePasswordMinimumLength":  4,
    "workProfilePasswordMinNumericCharacters":  null,
    "workProfilePasswordMinNonLetterCharacters":  null,
    "workProfilePasswordMinLetterCharacters":  null,
    "workProfilePasswordMinLowerCaseCharacters":  null,
    "workProfilePasswordMinUpperCaseCharacters":  null,
    "workProfilePasswordMinSymbolCharacters":  null,
    "workProfilePasswordMinutesOfInactivityBeforeScreenTimeout":  5,
    "workProfilePasswordPreviousPasswordBlockCount":  null,
    "workProfilePasswordSignInFailureCountBeforeFactoryReset":  10,
    "workProfilePasswordRequiredType":  "atLeastNumeric",
    "workProfileRequirePassword":  true,
    "securityRequireVerifyApps":  true,
    "vpnAlwaysOnPackageIdentifier":  null,
    "vpnEnableAlwaysOnLockdownMode":  false,
    "workProfileAllowWidgets":  false,
    "workProfileBlockPersonalAppInstallsFromUnknownSources":  true
}
"@