$MacOSDR = @"

{
    "@odata.type":  "#microsoft.graph.macOSGeneralDeviceConfiguration",
    "deviceManagementApplicabilityRuleOsEdition":  null,
    "deviceManagementApplicabilityRuleOsVersion":  null,
    "deviceManagementApplicabilityRuleDeviceMode":  null,
    "description":  "",
    "displayName":  "Portall - MacOS - Device restrictions",
    "compliantAppListType":  "none",
    "emailInDomainSuffixes":  [

                                ],
    "passwordBlockSimple":  true,
    "passwordExpirationDays":  null,
    "passwordMinimumCharacterSetCount":  null,
    "passwordMinimumLength":  4,
    "passwordMinutesOfInactivityBeforeLock":  0,
    "passwordMinutesOfInactivityBeforeScreenTimeout":  10,
    "passwordPreviousPasswordBlockCount":  null,
    "passwordRequiredType":  "deviceDefault",
    "passwordRequired":  true,
    "keychainBlockCloudSync":  false,
    "airPrintBlocked":  false,
    "airPrintForceTrustedTLS":  false,
    "airPrintBlockiBeaconDiscovery":  false,
    "safariBlockAutofill":  false,
    "cameraBlocked":  false,
    "iTunesBlockMusicService":  false,
    "spotlightBlockInternetResults":  false,
    "keyboardBlockDictation":  false,
    "definitionLookupBlocked":  false,
    "appleWatchBlockAutoUnlock":  false,
    "iTunesBlockFileSharing":  false,
    "iCloudBlockDocumentSync":  false,
    "iCloudBlockMail":  false,
    "iCloudBlockAddressBook":  false,
    "iCloudBlockCalendar":  false,
    "iCloudBlockReminders":  false,
    "iCloudBlockBookmarks":  false,
    "iCloudBlockNotes":  false,
    "airDropBlocked":  false,
    "passwordBlockModification":  false,
    "passwordBlockFingerprintUnlock":  false,
    "passwordBlockAutoFill":  false,
    "passwordBlockProximityRequests":  false,
    "passwordBlockAirDropSharing":  false,
    "softwareUpdatesEnforcedDelayInDays":  null,
    "softwareUpdatesForceDelayed":  false,
    "contentCachingBlocked":  false,
    "iCloudBlockPhotoLibrary":  false,
    "screenCaptureBlocked":  false,
    "classroomAppBlockRemoteScreenObservation":  false,
    "classroomAppForceUnpromptedScreenObservation":  false,
    "classroomForceAutomaticallyJoinClasses":  false,
    "classroomForceRequestPermissionToLeaveClasses":  false,
    "classroomForceUnpromptedAppAndDeviceLock":  false,
    "iCloudBlockActivityContinuation":  false,
    "compliantAppsList":  [

                            ]
}
"@